# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f851d636d7aed21b8b05e1e6c08fe700d7f31decbc22b38731a6af4f854848ac0eea06228c9413e961ca0b2e738c1940a79d6c3806ce22f8bfd7a666d5457468

test:
  secret_key_base: 64a042a3c38835b8dcc001f2ba32aa9a35ac2e3a61ebf9fa1ddcc5bd3f387d5c574c48d1eaf7f0ef4d04ab76a63d1c8d9f3b1738f11aba0662d08864aa4523d1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
